### ISSUE TITLE
NGFD crashes on pinephone

### ISSUE THREAD

**Issue by jmlich** [nemomobile-ux/main#51]
```
(gdb) r
Starting program: /usr/bin/ngfd -v
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[1.18446744073709550973] ERROR: core: unable to open plugin 'droid-vibrator'
Vibra upload effect: No space left on device
[1.18446744073709551186] ERROR: ffmemless: Could not load ngfd effects

(ngfd:4701): GLib-ERROR **: 18:23:42.999: ../glib/glib/gmem.c:169: failed to allocate 5726623164 bytes

Program received signal SIGTRAP, Trace/breakpoint trap.
0x0000fffff7b12790 in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x0000fffff7b12790 in  () at /usr/lib/libc.so.6
#1  0x0000fffff7acb6fc in raise () at /usr/lib/libc.so.6
#2  0x0000fffff7e02e10 in g_log_default_handler () at /usr/lib/libglib-2.0.so.0
#3  0x0000fffff7e0317c in g_logv () at /usr/lib/libglib-2.0.so.0
#4  0x0000fffff7e033c8 in g_log () at /usr/lib/libglib-2.0.so.0
#5  0x0000fffff7e0143c in g_malloc0 () at /usr/lib/libglib-2.0.so.0
#6  0x0000fffff7ddf92c in  () at /usr/lib/libglib-2.0.so.0
#7  0x0000fffff7de1b50 in g_hash_table_destroy () at /usr/lib/libglib-2.0.so.0
#8  0x0000fffff6b42e94 in  () at /usr/lib/ngf/libngfd_ffmemless.so
#9  0x0000aaaaaaaa83ac in n_core_initialize ()
#10 0x0000aaaaaaaa6364 in main ()
```

Is that patch used ?

https://github.com/sailfishos/ngfd/pull/8

If I remember correctly, this started after changing ngfd settings in sailfish os

**Comment by jmlich** [comment]
After using patch from pull request it is not crashing, but daemon is not started anyway:
```
[manjaro@pinephone ~]$ ngfd -v
[1.18446744073709550700] ERROR: core: unable to open plugin 'droid-vibrator'
Vibra upload effect: No space left on device
[1.18446744073709550954] ERROR: ffmemless: Could not load ngfd effects
[1.18446744073709550996] ERROR: core: sink 'ffmemless' failed to initialize
[1.18446744073709550996] ERROR: daemon: Initialization failed.
```
